apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cbxi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-cbxi@sha256:83cec288e3d184ec89aab3d3bc224142b7c696511f734ab25e4c45344b8bcb29
        name: my-nodejs
        resources: {}
status: {}
